services:

  app:
    image: sunjaegood/high-concurrency-ticketing-api:dev
    ports:
      - "8080:8080"
      - "9091:9091"
    env_file:
      - .env.dev
    environment:
      TZ: Asia/Seoul
    ulimits:
      nofile:
        soft: 200000
        hard: 200000