spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 30

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080
  tomcat:
    max-connections: 100000
    mbeanregistry:
      enabled: true # Tomcat 매트릭 수집하기 위한 설정
    threads:
      max: 300

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,prometheus
