spring:
  application:
    name: High_Concurrency_Ticketing
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      maximum-pool-size: 30

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

server:
  tomcat:
    max-connections: 100000
    mbeanregistry:
      enabled: true # Tomcat 매트릭 수집하기 위한 설정
    threads:
      max: 300

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus